### ISSUE TITLE
Ability to validate or transform each included file

### ISSUE THREAD

**Issue by joeyespo** [medikoo/modules-webmake#47]
For [a side project](http://github.com/joeyespo/gessojs), I'm running the bundled code through [a JS syntax checker](http://esprima.org/demo/validate.html) to catch errors before they get to the browser. The problem is, the line numbers are off because it isn't checking the individual files.

Is it possible to have a function called for each file webmake comes across (new / modified if `cached: true`), to do some kind of application-level validation? If not, I have a couple thoughts.
1. Add a `validate` option that takes a callback that returns a `true` if the file is valid, or a string/Error/object if not, which indicates the problem
2. Add a `transform` option that takes a callback that returns the actual code to use by webmake

For what I'm doing, the former is fine, but the latter is more general (and slightly more complex in implementation). In either case, if an error is raised, that can be passed to `err` in webmake's callback.

Is this already possible or in the roadmap? If not, what are your thoughts?

**Comment by joeyespo** [comment]
Meant to comment on this a *while* ago. This change was exactly what I needed :-) Been using it ever since you published it. Thanks!

**Comment by medikoo** [comment]
:+1:
