### ISSUE TITLE
Extension for EJS

### ISSUE THREAD

**Issue by tswaters** [medikoo/modules-webmake#49]
I created an extension for EJS, 

https://github.com/tswaters/webmake-ejs

**Comment by medikoo** [comment]
Thanks @tswaters looks nice, I've listed you're plugin in [documentation](https://github.com/medikoo/modules-webmake#js)

Still, if in future you'll find a possibility to not rely on `ejs` being a global, but instead use it via something as `require('ejs')` it'll be a great improvement. Using globals contradicts beauty of CJS.

**Comment by tswaters** [comment]
I agree fully.  Initially I didn't notice the "client" option (which is similar to the 'precompile' function in handlebars)... I've pushed up an updated version, also published to npm.
