### ISSUE TITLE
Extensions don't work for js files

### ISSUE THREAD

**Issue by raffomania** [medikoo/modules-webmake#51]
When defining an extension of type js for the filename extension js, my extension won't get called.
I guess this is caused by the following line: https://github.com/medikoo/modules-webmake/blob/master/lib/parser.js#L113
Is this intended?

Edit: I'd use a transform, but I would also like to have custom source maps support...

**Comment by medikoo** [comment]
@raffomania will support for source maps in transforms solve your issue?

e.g. instead of returning just _code_ from transform you may return `{ code: code, sourceMap: sourceMap }`. I can open support for passing source maps that way.

Let me know

**Comment by raffomania** [comment]
@medikoo That would solve my problem, yes!
One question though: Conceptually, extensions seem to be for non-js files only. Why is there a js type for extensions?

**Comment by raffomania** [comment]
Sorry for the close, it was a misclick ^^

**Comment by medikoo** [comment]
> One question though: Conceptually, extensions seem to be for non-js files only. Why is there a js type for extensions?

Extensions are for some other formats that can be compiled to one of the natively supported types (which is .js, .json, .css, .html).
So best use cases are e.g. CoffeeScript (compiles to JS), Less (compiles to CSS), YAML (compiles to JSON)

**Comment by raffomania** [comment]
Ah, this clarifies a lot. Am I right that 
- filename extension is for the input file
- extension type is for the output file
? 
If so, it would be cool if this was explained in the docs.

**Comment by medikoo** [comment]
I've improved documentation, so at least in extensions examples it's clear that one is about extension of compiled format, and other one is about extension of native type. If you have any other suggestions how documentation should be improved PR's are welcome.

I've also added source map support to transforms. So now you should be able to achieve what you need via transform option. See end sentence in _transform_ documentation -> https://github.com/medikoo/modules-webmake#transform-function-programmatical-usage-only

It's published as v0.3.38

**Comment by raffomania** [comment]
thanks a lot!
