### ISSUE TITLE
Wrong transformation for empty module for special case

### ISSUE THREAD

**Issue by miherlosev** [medikoo/modules-webmake#52]
1) Download the sample - http://content.screencast.com/users/miherlosev/folders/TestCafe/media/4814bdd8-ea5c-42dd-b642-ff5bf16542c8/babel-runtime-core-js_2.zip?downloadOnly=true.
2) Install node modules and run the gulp task.
3) Inspect /processed/index.js. It contains strange code:
`"es6.object.to-string.js": function (exports, module, require) { 
       [object Object] 
},`
4) The code has been generated for the module 'babel-runtime\node_modules\core-js\library\modules\es6.object.to-string.js' which is empty.

Simple for empty module all works good.

**Comment by medikoo** [comment]
Indeed it happened when source maps functionality was used.

It's fixed now, and will be published in 2 minutes as v0.3.40
