### ISSUE TITLE
Cannot bundle module 'promise'

### ISSUE THREAD

**Issue by miherlosev** [medikoo/modules-webmake#53]
1)Download sample - http://content.screencast.com/users/miherlosev/folders/TestCafe/media/83a40b2d-b64c-4aef-b32d-acced9cbe07c/webmake_promise.zip?downloadOnly=true
2)Extract, install modules, run gulp task
3)Get error:

`Cannot require "domain" (as in 'c:\Bugs\webmake_promise\node_modules\promise\node_modules\asap\raw.js').
       Native node.js modules are not ported to client-side. You can however provide an alternative version of this module in your node_modules path, it will be picked up by Webmake.`

**Comment by medikoo** [comment]
It's expected behavior, error message says everything.

You need to either provide version of `domain` naturally in node_modules, or if it's a bundle intended for Node.js, then add `ingoreErrors: true` options

**Comment by nathan7** [comment]
`asap`'s `package.json` includes the `browser` field for compatible bundlers (Browserify, Webpack): https://github.com/kriskowal/asap/blob/d7359b771fb3ff41f8bfcbb1fa00ade7126fc622/package.json#L19-L23

**Comment by medikoo** [comment]
Webmake at this point doesn't support `browser` field, it's environment agnostic CJS bundler, I also believe that most of issues can be solved without using `browser` setting.
