### ISSUE TITLE
It is possible to perform tree shaking for bundled module?

### ISSUE THREAD

**Issue by miherlosev** [medikoo/modules-webmake#55]
As in https://webpack.js.org/guides/tree-shaking/

**Comment by medikoo** [comment]
@miherlosev no, and technically tree-shaking doesn't make much sense in case of CJS modules.

Tree-shaking is about stripping module out of exports that are not being used by module consumers, while contrary to ESM (where we can export many values), in CJS we can export only _one_ (exposed on `module.exports`).

Module with multiple exports written in ESM format if translated to CJS should result with multiple CJS modules.

I believe in WebPack it's strictly about ESM.
