### ISSUE TITLE
deprecated library during installing

### ISSUE THREAD

**Issue by fabioricali** [medikoo/modules-webmake#56]
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher

**Comment by medikoo** [comment]
Great thanks for reporting. It was due to [fs2](https://www.npmjs.com/package/fs2) relied on old minimatch. It was updated just now to rely on minimatch@3 and published as 0.2.6.

So just be sure that webmake installs with most recent fs2@0.2.6 and deprecation message should no longer appear.

**Comment by fabioricali** [comment]
Perfect!
thanks :)
