### ISSUE TITLE
Comparison ... may cause unexpected type coercion

### ISSUE THREAD

**Issue by fabioricali** [medikoo/modules-webmake#57]
Hi,

in code generated by webmake there may be a coercion issue in this part:
`while ((dir = path.shift()) != null) `
[https://github.com/medikoo/modules-webmake/blob/master/lib/webmake.tpl#L32](https://github.com/medikoo/modules-webmake/blob/master/lib/webmake.tpl#L32
)
You can use !== instead !=

**Comment by medikoo** [comment]
@fabioricali it's intentional to eliminate both `null` and `undefined`. Still it's probably just `undefined` that can land there, but then it would be problematic to refer to `undefined` directly as it's not safe in ES3 envs.

Why it's the issue for you? Do you pass generated files through linter?

**Comment by fabioricali** [comment]
Sorry! it's not real issue for me... I have reported a warning of my IDE :)
thanks for reply.

**Comment by medikoo** [comment]
Ok, good. I'm closing it then :)

**Comment by fabioricali** [comment]
anyway your module is very fast and deserves more popularity ;)
